server:
  port: 5000
  servlet:
    context-path: /sanjivani
  error:
    include-message: always
spring:
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    generate-ddl: true
    show-sql: true
  datasource:
    url: "jdbc:postgresql://sanjivani-db.c3mmsao86frk.ap-south-1.rds.amazonaws.com:5432/Sanjivani"
    username: sanjivanidbadmin
    password: lQBF2JcA6IFzPMW0VYcV
    hikari:
      data-source-properties:
        useUnicode: true
        characterEncoding: UTF-8
